/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "status-critical": "#ff4d00",
        "secondary-fixed-dim": "#c0c1ff",
        "on-secondary-fixed-variant": "#2f2ebe",
        "on-background": "#e3e2e7",
        "secondary": "#c0c1ff",
        "on-primary-fixed": "#002022",
        "outline": "#849495",
        "on-tertiary-container": "#725e00",
        "surface-variant": "#343439",
        "error-container": "#93000a",
        "secondary-container": "#3131c0",
        "on-surface-variant": "#b9cacb",
        "surface-container-lowest": "#0d0e12",
        "tertiary-fixed-dim": "#e8c423",
        "tertiary-container": "#fed83a",
        "on-error": "#690005",
        "inverse-primary": "#00696f",
        "surface-dim": "#121317",
        "primary": "#e1fdff",
        "on-secondary": "#1000a9",
        "on-secondary-fixed": "#07006c",
        "tertiary": "#fff6e4",
        "surface-tint": "#00dbe7",
        "primary-container": "#00f2ff",
        "grid-line": "#1f2937",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "on-tertiary": "#3b2f00",
        "on-surface": "#e3e2e7",
        "on-primary-container": "#006a71",
        "on-tertiary-fixed-variant": "#554500",
        "tertiary-fixed": "#ffe173",
        "status-warning": "#f59e0b",
        "on-tertiary-fixed": "#221b00",
        "background": "#121317",
        "surface": "#121317",
        "primary-fixed-dim": "#00dbe7",
        "inverse-on-surface": "#2f3035",
        "status-danger": "#ef4444",
        "surface-container": "#1f1f24",
        "surface-elevated": "#161922",
        "surface-container-high": "#292a2e",
        "surface-container-highest": "#343439",
        "status-success": "#10b981",
        "surface-container-low": "#1a1b20",
        "on-primary": "#00363a",
        "primary-fixed": "#74f5ff",
        "outline-variant": "#3a494b",
        "on-secondary-container": "#b0b2ff",
        "on-primary-fixed-variant": "#004f54",
        "secondary-fixed": "#e1e0ff",
        "inverse-surface": "#e3e2e7",
        "surface-bright": "#38393d",

        // Compatibility bridges
        accent: {
          blue: "#00f2ff",
          cyan: "#00dbe7",
          emerald: "#10b981",
          amber: "#f59e0b",
          rose: "#ff4d00",
          purple: "#c0c1ff",
          indigo: "#3131c0",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.25rem",
      },
      spacing: {
        "panel-padding": "20px",
        unit: "4px",
        "sidebar-width": "64px",
        gutter: "16px",
        "topbar-height": "64px",
        header: "64px",
        iconbar: "64px",
        drawer: "400px",
      },
      fontFamily: {
        "headline-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-metrics": ["var(--font-inter)", "Inter", "sans-serif"],
        "data-mono": ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        mono: ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "display-metrics": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "data-mono": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "slide-in-right": {
          "0%": { transform: "translateX(100%)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        "slide-in-up": {
          "0%": { transform: "translateY(16px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "slide-in-left": {
          "0%": { transform: "translateX(-100%)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        "pulse-critical": {
          "0%": { boxShadow: "0 0 0 0 rgba(255, 77, 0, 0.7)" },
          "70%": { boxShadow: "0 0 0 15px rgba(255, 77, 0, 0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(255, 77, 0, 0)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.2s ease-out",
        "slide-in-right": "slide-in-right 0.25s cubic-bezier(0.16,1,0.3,1)",
        "slide-in-up": "slide-in-up 0.2s ease-out",
        "slide-in-left": "slide-in-left 0.2s ease-out",
        "pulse-critical": "pulse-critical 2s infinite",
      },
    },
  },
  plugins: [],
};
