import { NetworkSummary } from "@/types";

export const getNagpurFallbackSummary = (): NetworkSummary => ({
  timestamp: new Date().toISOString(),
  uptimeSeconds: 3600,
  isDemoMode: false,
  metrics: {
    averageSpeedKmh: 36.8,
    averageCongestionScore: 38.4,
    criticalJunctions: 0,
    highRiskJunctions: 1,
    activeIncidentsCount: 0,
    activeDeploymentsCount: 2,
    availableOfficersCount: 4,
  },
  liveStates: {
    seg_wardha_north: {
      segmentId: "seg_wardha_north",
      name: "Wardha Road (Rahate Colony → Sitabuldi Flyover)",
      fromJunction: "j_wardha_rd",
      toJunction: "j_sitabuldi",
      currentSpeed: 38.0,
      freeFlowSpeed: 50.0,
      currentTravelTime: 180,
      freeFlowTravelTime: 135,
      delaySeconds: 45,
      delayPercent: 33,
      congestionScore: 38,
      riskScore: 35,
      riskSeverity: "LOW",
      vehiclesPerMinute: 42,
      confidence: 0.94,
      freshnessSeconds: 3,
      closure: false,
      incidentState: false,
      source: "tomtom_fused_cv",
      geometry: [
        [79.0754, 21.1278],
        [79.0792, 21.1356],
        [79.0834, 21.1466],
      ],
      updatedAt: new Date().toISOString(),
    },
    seg_central_west: {
      segmentId: "seg_central_west",
      name: "Central Avenue (Sitabuldi → Agrasen Sq)",
      fromJunction: "j_sitabuldi",
      toJunction: "j_agrasen_sq",
      currentSpeed: 32.0,
      freeFlowSpeed: 45.0,
      currentTravelTime: 220,
      freeFlowTravelTime: 160,
      delaySeconds: 60,
      delayPercent: 37,
      congestionScore: 44,
      riskScore: 42,
      riskSeverity: "MODERATE",
      vehiclesPerMinute: 38,
      confidence: 0.96,
      freshnessSeconds: 2,
      closure: false,
      incidentState: false,
      source: "tomtom_fused_cv",
      geometry: [
        [79.0834, 21.1466],
        [79.095, 21.15],
        [79.1055, 21.1532],
      ],
      updatedAt: new Date().toISOString(),
    },
    seg_medical_south: {
      segmentId: "seg_medical_south",
      name: "Medical College Rd (Ajni Overbridge → Medical Sq)",
      fromJunction: "j_medical_sq",
      toJunction: "j_sitabuldi",
      currentSpeed: 36.0,
      freeFlowSpeed: 45.0,
      currentTravelTime: 190,
      freeFlowTravelTime: 150,
      delaySeconds: 40,
      delayPercent: 26,
      congestionScore: 32,
      riskScore: 28,
      riskSeverity: "LOW",
      vehiclesPerMinute: 31,
      confidence: 0.92,
      freshnessSeconds: 4,
      closure: false,
      incidentState: false,
      source: "tomtom_fused_cv",
      geometry: [
        [79.0968, 21.1344],
        [79.09, 21.14],
        [79.0834, 21.1466],
      ],
      updatedAt: new Date().toISOString(),
    },
    seg_west_dharampeth: {
      segmentId: "seg_west_dharampeth",
      name: "West High Court Rd (Dharampeth → Law College Sq)",
      fromJunction: "j_dharampeth",
      toJunction: "j_sitabuldi",
      currentSpeed: 42.0,
      freeFlowSpeed: 50.0,
      currentTravelTime: 160,
      freeFlowTravelTime: 135,
      delaySeconds: 25,
      delayPercent: 18,
      congestionScore: 24,
      riskScore: 22,
      riskSeverity: "LOW",
      vehiclesPerMinute: 28,
      confidence: 0.95,
      freshnessSeconds: 3,
      closure: false,
      incidentState: false,
      source: "tomtom_fused_cv",
      geometry: [
        [79.065, 21.145],
        [79.074, 21.146],
        [79.0834, 21.1466],
      ],
      updatedAt: new Date().toISOString(),
    },
  },
  junctionRisks: {
    j_sitabuldi: {
      junctionId: "j_sitabuldi",
      name: "Sitabuldi Interchange (Variety Sq)",
      lat: 21.1466,
      lon: 79.0834,
      riskScore: 48.0,
      severity: "MODERATE",
      congestionFactor: 42.0,
      incidentFactor: 0.0,
      criticalityFactor: 94.0,
      exposureFactor: 60.0,
      queueFactor: 25.0,
      responseGapFactor: 20.0,
      whyExplanation: "Primary network junction bridging East-West Nagpur corridors with moderate peak-hour flow.",
      policeAssigned: true,
      confidence: 0.96,
      timestamp: new Date().toISOString(),
    },
    j_wardha_rd: {
      junctionId: "j_wardha_rd",
      name: "Wardha Road T-Point (Rahate Colony)",
      lat: 21.1278,
      lon: 79.0754,
      riskScore: 36.0,
      severity: "LOW",
      congestionFactor: 32.0,
      incidentFactor: 0.0,
      criticalityFactor: 75.0,
      exposureFactor: 45.0,
      queueFactor: 15.0,
      responseGapFactor: 10.0,
      whyExplanation: "Nominal vehicular movement towards Airport / MIHAN corridor.",
      policeAssigned: true,
      confidence: 0.94,
      timestamp: new Date().toISOString(),
    },
    j_medical_sq: {
      junctionId: "j_medical_sq",
      name: "Medical Square (Ajni Approach)",
      lat: 21.1344,
      lon: 79.0968,
      riskScore: 42.0,
      severity: "MODERATE",
      congestionFactor: 38.0,
      incidentFactor: 0.0,
      criticalityFactor: 80.0,
      exposureFactor: 55.0,
      queueFactor: 20.0,
      responseGapFactor: 15.0,
      whyExplanation: "Hospital emergency corridor with steady commercial and ambulance traffic.",
      policeAssigned: false,
      confidence: 0.92,
      timestamp: new Date().toISOString(),
    },
    j_agrasen_sq: {
      junctionId: "j_agrasen_sq",
      name: "Central Avenue (Agrasen Sq)",
      lat: 21.1532,
      lon: 79.1055,
      riskScore: 38.0,
      severity: "LOW",
      congestionFactor: 40.0,
      incidentFactor: 0.0,
      criticalityFactor: 70.0,
      exposureFactor: 50.0,
      queueFactor: 20.0,
      responseGapFactor: 10.0,
      whyExplanation: "Commercial arterial connecting Gandhibagh and Itwari wholesale hubs.",
      policeAssigned: false,
      confidence: 0.95,
      timestamp: new Date().toISOString(),
    },
  },
  incidents: [],
  deployments: [
    {
      deploymentId: "dep_01",
      recommendationId: "rec_init_01",
      officerId: "off_01",
      officerName: "Insp. Ramesh Patil (MP-01)",
      junctionId: "j_sitabuldi",
      junctionName: "Sitabuldi Interchange",
      status: "ACCEPTED",
      assignedAt: new Date().toISOString(),
      etaMinutes: 0.0,
      riskReductionExpected: 14.5,
      operatorNotes: "Static patrol on flyover approach.",
    },
  ],
  recommendations: [],
  officers: [
    {
      id: "off_01",
      name: "Insp. Ramesh Patil",
      badgeNumber: "MP-01",
      rank: "Inspector",
      lat: 21.1466,
      lon: 79.0834,
      currentJunctionId: "j_sitabuldi",
      isAvailable: false,
      shiftStatus: "ON_DUTY",
      contactNumber: "+91 712-256-4401",
    },
    {
      id: "off_02",
      name: "SI Rajesh Sharma",
      badgeNumber: "MP-04",
      rank: "Sub-Inspector",
      lat: 21.142,
      lon: 79.08,
      isAvailable: true,
      shiftStatus: "ON_DUTY",
      contactNumber: "+91 712-256-4404",
    },
    {
      id: "off_03",
      name: "HC Anil Deshmukh",
      badgeNumber: "MP-09",
      rank: "Head Constable",
      lat: 21.13,
      lon: 79.078,
      isAvailable: true,
      shiftStatus: "ON_DUTY",
      contactNumber: "+91 712-256-4409",
    },
    {
      id: "off_04",
      name: "Constable Sunita Gaikwad",
      badgeNumber: "MP-12",
      rank: "Constable",
      lat: 21.138,
      lon: 79.092,
      isAvailable: true,
      shiftStatus: "ON_DUTY",
      contactNumber: "+91 712-256-4412",
    },
  ],
  cameras: [
    {
      cameraId: "cam_sitabuldi_01",
      name: "Sitabuldi North (Variety Sq Approach)",
      junctionId: "j_sitabuldi",
      lat: 21.1468,
      lon: 79.0832,
      sourceType: "EDGE_OPTICAL",
      direction: "NORTHBOUND",
      isCalibrated: true,
      enabled: true,
    },
    {
      cameraId: "cam_wardha_01",
      name: "Wardha Rd T-Point (Rahate Flyover)",
      junctionId: "j_wardha_rd",
      lat: 21.128,
      lon: 79.0756,
      sourceType: "EDGE_OPTICAL",
      direction: "SOUTHBOUND",
      isCalibrated: true,
      enabled: true,
    },
    {
      cameraId: "cam_medical_01",
      name: "Medical Sq East (Ajni Approach)",
      junctionId: "j_medical_sq",
      lat: 21.1344,
      lon: 79.0968,
      sourceType: "EDGE_OPTICAL",
      direction: "EASTBOUND",
      isCalibrated: true,
      enabled: true,
    },
    {
      cameraId: "cam_central_01",
      name: "Central Ave (Agrasen Sq Gandhibagh)",
      junctionId: "j_agrasen_sq",
      lat: 21.1534,
      lon: 79.1057,
      sourceType: "EDGE_OPTICAL",
      direction: "WESTBOUND",
      isCalibrated: true,
      enabled: true,
    },
  ],
});

export const getNagpurDisruptedSummary = (): NetworkSummary => {
  const base = getNagpurFallbackSummary();
  base.isDemoMode = true;
  base.metrics.criticalJunctions = 1;
  base.metrics.activeIncidentsCount = 1;
  base.metrics.averageSpeedKmh = 21.4;
  base.metrics.averageCongestionScore = 76.5;

  base.incidents = [
    {
      id: "demo_inc_sitabuldi_01",
      title: "Multi-Vehicle Collision at Sitabuldi Interchange (Variety Sq)",
      incidentType: "accident",
      severity: "CRITICAL",
      lat: 21.1466,
      lon: 79.0834,
      affectedRoadIds: ["seg_wardha_north", "seg_central_west"],
      blockedLanes: 2,
      capacityReductionPct: 65.0,
      startTime: new Date().toISOString(),
      source: "emergency_cctv_cad",
      confidence: 0.98,
      description: "Major 3-vehicle collision blocking two inbound lanes at Variety Sq flyover descent. Heavy queuing developing.",
      isSimulated: true,
    },
  ];

  base.liveStates.seg_wardha_north.currentSpeed = 11.0;
  base.liveStates.seg_wardha_north.congestionScore = 88.0;
  base.liveStates.seg_wardha_north.riskScore = 92.0;
  base.liveStates.seg_wardha_north.riskSeverity = "CRITICAL";
  base.liveStates.seg_wardha_north.incidentState = true;

  base.liveStates.seg_central_west.currentSpeed = 16.0;
  base.liveStates.seg_central_west.congestionScore = 74.0;
  base.liveStates.seg_central_west.riskScore = 78.0;
  base.liveStates.seg_central_west.riskSeverity = "HIGH";

  base.junctionRisks.j_sitabuldi.riskScore = 92.4;
  base.junctionRisks.j_sitabuldi.severity = "CRITICAL";
  base.junctionRisks.j_sitabuldi.incidentFactor = 95.0;
  base.junctionRisks.j_sitabuldi.congestionFactor = 88.0;
  base.junctionRisks.j_sitabuldi.policeAssigned = false;
  base.junctionRisks.j_sitabuldi.whyExplanation = "Multi-vehicle collision blocking 2 lanes on Variety Sq flyover descent with upstream queuing on Wardha Rd.";

  base.recommendations = [
    {
      recommendationId: "rec_sitabuldi_demo",
      targetJunctionId: "j_sitabuldi",
      targetJunctionName: "Sitabuldi Interchange",
      officerId: "off_02",
      officerName: "SI Rajesh Sharma (MP-04)",
      expectedRiskReduction: 24.8,
      estimatedArrivalMinutes: 3.4,
      priority: "CRITICAL",
      rationale: "Incident shockwave at Variety Sq flyover descent causing 110m queue spillback. Immediate diversion control required.",
      confidence: 0.96,
      timestamp: new Date().toISOString(),
    },
  ];

  return base;
};
