from typing import Dict, List, Tuple
from app.domain.models import Junction, RoadSegment, RoadClass, Camera, Officer, CountingLine, QueueZone

# Reference Nagpur Center
NAGPUR_CENTER_LAT = 21.1458
NAGPUR_CENTER_LON = 79.0882
NAGPUR_BBOX = [79.0200, 21.0900, 79.1600, 21.1800]  # [min_lon, min_lat, max_lon, max_lat]

# 1. Nagpur Key Junctions
NAGPUR_JUNCTIONS: Dict[str, Junction] = {
    "j_sitabuldi": Junction(
        id="j_sitabuldi",
        name="Sitabuldi Interchange (Variety Sq)",
        lat=21.1466,
        lon=79.0834,
        connectedRoads=[
            "seg_wardha_north", "seg_wardha_south",
            "seg_west_dharampeth", "seg_east_cotton_mkt",
            "seg_sadar_south", "seg_central_west"
        ],
        importance=5.0,
        betweennessCentrality=0.95,
        isSignalized=True,
    ),
    "j_wardha_tpoint": Junction(
        id="j_wardha_tpoint",
        name="Rahate Colony T-Point (Wardha Rd)",
        lat=21.1278,
        lon=79.0754,
        connectedRoads=["seg_wardha_north", "seg_wardha_south", "seg_ajni_west", "seg_shankarnagar_se"],
        importance=4.8,
        betweennessCentrality=0.88,
        isSignalized=True,
    ),
    "j_medical_sq": Junction(
        id="j_medical_sq",
        name="Medical Square (GMC Nagpur)",
        lat=21.1351,
        lon=79.0988,
        connectedRoads=["seg_medical_north", "seg_medical_south", "seg_ajni_east", "seg_cotton_south"],
        importance=4.5,
        betweennessCentrality=0.82,
        isSignalized=True,
    ),
    "j_cotton_market": Junction(
        id="j_cotton_market",
        name="Cotton Market Square (Railway South)",
        lat=21.1504,
        lon=79.0911,
        connectedRoads=["seg_east_cotton_mkt", "seg_cotton_south", "seg_central_ave_sw"],
        importance=4.6,
        betweennessCentrality=0.85,
        isSignalized=True,
    ),
    "j_central_ave": Junction(
        id="j_central_ave",
        name="Central Avenue (Agrasen Square)",
        lat=21.1532,
        lon=79.1055,
        connectedRoads=["seg_central_west", "seg_central_ave_sw", "seg_central_east_pardi"],
        importance=4.7,
        betweennessCentrality=0.89,
        isSignalized=True,
    ),
    "j_dharampeth": Junction(
        id="j_dharampeth",
        name="Dharampeth (Law College Square)",
        lat=21.1442,
        lon=79.0621,
        connectedRoads=["seg_west_dharampeth", "seg_shankarnagar_north"],
        importance=4.2,
        betweennessCentrality=0.75,
        isSignalized=True,
    ),
    "j_shankarnagar": Junction(
        id="j_shankarnagar",
        name="Shankar Nagar Square",
        lat=21.1378,
        lon=79.0585,
        connectedRoads=["seg_shankarnagar_north", "seg_shankarnagar_se", "seg_hingna_north"],
        importance=4.1,
        betweennessCentrality=0.74,
        isSignalized=True,
    ),
    "j_sadar": Junction(
        id="j_sadar",
        name="Sadar (Liberty Cinema Square)",
        lat=21.1630,
        lon=79.0792,
        connectedRoads=["seg_sadar_south", "seg_sadar_north"],
        importance=4.4,
        betweennessCentrality=0.79,
        isSignalized=True,
    ),
    "j_ajni": Junction(
        id="j_ajni",
        name="Ajni Square (Railway Overbridge)",
        lat=21.1189,
        lon=79.0820,
        connectedRoads=["seg_ajni_west", "seg_ajni_east", "seg_manewada_north"],
        importance=4.3,
        betweennessCentrality=0.80,
        isSignalized=True,
    ),
    "j_manewada": Junction(
        id="j_manewada",
        name="Manewada Square (Ring Road)",
        lat=21.1095,
        lon=79.0965,
        connectedRoads=["seg_manewada_north", "seg_ring_road_east"],
        importance=4.0,
        betweennessCentrality=0.72,
        isSignalized=True,
    ),
    "j_hingna_tpoint": Junction(
        id="j_hingna_tpoint",
        name="Hingna Road T-Point (Subhash Nagar)",
        lat=21.1205,
        lon=79.0432,
        connectedRoads=["seg_hingna_north"],
        importance=4.0,
        betweennessCentrality=0.70,
        isSignalized=True,
    ),
    "j_pardi": Junction(
        id="j_pardi",
        name="Pardi Naka (Bhandara Road Flyover)",
        lat=21.1528,
        lon=79.1462,
        connectedRoads=["seg_central_east_pardi"],
        importance=3.9,
        betweennessCentrality=0.68,
        isSignalized=True,
    ),
}

# 2. Nagpur Key Road Segments (GeoJSON line strings [lon, lat])
NAGPUR_ROAD_SEGMENTS: Dict[str, RoadSegment] = {
    "seg_wardha_north": RoadSegment(
        id="seg_wardha_north",
        osmId="osm_wardha_n_01",
        name="Wardha Road (Rahate Colony to Sitabuldi)",
        fromJunction="j_wardha_tpoint",
        toJunction="j_sitabuldi",
        roadClass=RoadClass.PRIMARY,
        lanes=3,
        lengthMeters=2400.0,
        speedLimitKmh=60.0,
        capacityVehiclesPerHour=3600,
        importance=4.9,
        betweennessCentrality=0.92,
        geometry=[
            [79.0754, 21.1278],
            [79.0775, 21.1340],
            [79.0805, 21.1405],
            [79.0834, 21.1466],
        ],
    ),
    "seg_wardha_south": RoadSegment(
        id="seg_wardha_south",
        osmId="osm_wardha_s_01",
        name="Wardha Road (Sitabuldi to Rahate Colony)",
        fromJunction="j_sitabuldi",
        toJunction="j_wardha_tpoint",
        roadClass=RoadClass.PRIMARY,
        lanes=3,
        lengthMeters=2400.0,
        speedLimitKmh=60.0,
        capacityVehiclesPerHour=3600,
        importance=4.9,
        betweennessCentrality=0.92,
        geometry=[
            [79.0834, 21.1466],
            [79.0805, 21.1405],
            [79.0775, 21.1340],
            [79.0754, 21.1278],
        ],
    ),
    "seg_west_dharampeth": RoadSegment(
        id="seg_west_dharampeth",
        osmId="osm_west_dh_01",
        name="North Ambazari Road (Sitabuldi to Dharampeth)",
        fromJunction="j_sitabuldi",
        toJunction="j_dharampeth",
        roadClass=RoadClass.PRIMARY,
        lanes=2,
        lengthMeters=2250.0,
        speedLimitKmh=50.0,
        capacityVehiclesPerHour=2400,
        importance=4.3,
        betweennessCentrality=0.76,
        geometry=[
            [79.0834, 21.1466],
            [79.0730, 21.1455],
            [79.0621, 21.1442],
        ],
    ),
    "seg_east_cotton_mkt": RoadSegment(
        id="seg_east_cotton_mkt",
        osmId="osm_cotton_01",
        name="Manas Chowk to Cotton Market Arterial",
        fromJunction="j_sitabuldi",
        toJunction="j_cotton_market",
        roadClass=RoadClass.PRIMARY,
        lanes=2,
        lengthMeters=950.0,
        speedLimitKmh=40.0,
        capacityVehiclesPerHour=2000,
        importance=4.5,
        betweennessCentrality=0.84,
        geometry=[
            [79.0834, 21.1466],
            [79.0870, 21.1485],
            [79.0911, 21.1504],
        ],
    ),
    "seg_central_west": RoadSegment(
        id="seg_central_west",
        osmId="osm_central_w_01",
        name="Central Avenue (Sitabuldi to Agrasen Sq)",
        fromJunction="j_sitabuldi",
        toJunction="j_central_ave",
        roadClass=RoadClass.PRIMARY,
        lanes=3,
        lengthMeters=2450.0,
        speedLimitKmh=50.0,
        capacityVehiclesPerHour=3400,
        importance=4.8,
        betweennessCentrality=0.90,
        geometry=[
            [79.0834, 21.1466],
            [79.0920, 21.1495],
            [79.1000, 21.1518],
            [79.1055, 21.1532],
        ],
    ),
    "seg_central_east_pardi": RoadSegment(
        id="seg_central_east_pardi",
        osmId="osm_central_e_01",
        name="Central Avenue Extension (Agrasen Sq to Pardi Naka)",
        fromJunction="j_central_ave",
        toJunction="j_pardi",
        roadClass=RoadClass.PRIMARY,
        lanes=3,
        lengthMeters=4300.0,
        speedLimitKmh=60.0,
        capacityVehiclesPerHour=3600,
        importance=4.2,
        betweennessCentrality=0.73,
        geometry=[
            [79.1055, 21.1532],
            [79.1250, 21.1530],
            [79.1462, 21.1528],
        ],
    ),
    "seg_sadar_south": RoadSegment(
        id="seg_sadar_south",
        osmId="osm_sadar_01",
        name="Residency Road (Sitabuldi to Sadar)",
        fromJunction="j_sitabuldi",
        toJunction="j_sadar",
        roadClass=RoadClass.PRIMARY,
        lanes=2,
        lengthMeters=1900.0,
        speedLimitKmh=50.0,
        capacityVehiclesPerHour=2200,
        importance=4.4,
        betweennessCentrality=0.78,
        geometry=[
            [79.0834, 21.1466],
            [79.0815, 21.1540],
            [79.0792, 21.1630],
        ],
    ),
    "seg_shankarnagar_north": RoadSegment(
        id="seg_shankarnagar_north",
        osmId="osm_sn_n_01",
        name="West High Court Road (Dharampeth to Shankar Nagar)",
        fromJunction="j_dharampeth",
        toJunction="j_shankarnagar",
        roadClass=RoadClass.SECONDARY,
        lanes=2,
        lengthMeters=850.0,
        speedLimitKmh=40.0,
        capacityVehiclesPerHour=1800,
        importance=4.0,
        betweennessCentrality=0.71,
        geometry=[
            [79.0621, 21.1442],
            [79.0600, 21.1410],
            [79.0585, 21.1378],
        ],
    ),
    "seg_shankarnagar_se": RoadSegment(
        id="seg_shankarnagar_se",
        osmId="osm_sn_se_01",
        name="Bajaj Nagar Corridor (Shankar Nagar to Rahate Colony)",
        fromJunction="j_shankarnagar",
        toJunction="j_wardha_tpoint",
        roadClass=RoadClass.SECONDARY,
        lanes=2,
        lengthMeters=2100.0,
        speedLimitKmh=45.0,
        capacityVehiclesPerHour=2000,
        importance=4.1,
        betweennessCentrality=0.77,
        geometry=[
            [79.0585, 21.1378],
            [79.0670, 21.1325],
            [79.0754, 21.1278],
        ],
    ),
    "seg_ajni_west": RoadSegment(
        id="seg_ajni_west",
        osmId="osm_ajni_w_01",
        name="Congress Nagar Link (Rahate Colony to Ajni Sq)",
        fromJunction="j_wardha_tpoint",
        toJunction="j_ajni",
        roadClass=RoadClass.PRIMARY,
        lanes=2,
        lengthMeters=1200.0,
        speedLimitKmh=50.0,
        capacityVehiclesPerHour=2400,
        importance=4.3,
        betweennessCentrality=0.79,
        geometry=[
            [79.0754, 21.1278],
            [79.0790, 21.1230],
            [79.0820, 21.1189],
        ],
    ),
    "seg_ajni_east": RoadSegment(
        id="seg_ajni_east",
        osmId="osm_ajni_e_01",
        name="Medical College Road (Ajni Sq to Medical Sq)",
        fromJunction="j_ajni",
        toJunction="j_medical_sq",
        roadClass=RoadClass.PRIMARY,
        lanes=2,
        lengthMeters=2400.0,
        speedLimitKmh=45.0,
        capacityVehiclesPerHour=2200,
        importance=4.4,
        betweennessCentrality=0.81,
        geometry=[
            [79.0820, 21.1189],
            [79.0910, 21.1270],
            [79.0988, 21.1351],
        ],
    ),
    "seg_cotton_south": RoadSegment(
        id="seg_cotton_south",
        osmId="osm_ct_s_01",
        name="Great Nag Road (Medical Sq to Cotton Market)",
        fromJunction="j_medical_sq",
        toJunction="j_cotton_market",
        roadClass=RoadClass.PRIMARY,
        lanes=2,
        lengthMeters=1950.0,
        speedLimitKmh=45.0,
        capacityVehiclesPerHour=2200,
        importance=4.5,
        betweennessCentrality=0.83,
        geometry=[
            [79.0988, 21.1351],
            [79.0950, 21.1430],
            [79.0911, 21.1504],
        ],
    ),
    "seg_central_ave_sw": RoadSegment(
        id="seg_central_ave_sw",
        osmId="osm_ca_sw_01",
        name="Gandhi Putla Link (Cotton Market to Agrasen Sq)",
        fromJunction="j_cotton_market",
        toJunction="j_central_ave",
        roadClass=RoadClass.SECONDARY,
        lanes=2,
        lengthMeters=1550.0,
        speedLimitKmh=40.0,
        capacityVehiclesPerHour=1900,
        importance=4.2,
        betweennessCentrality=0.76,
        geometry=[
            [79.0911, 21.1504],
            [79.0990, 21.1518],
            [79.1055, 21.1532],
        ],
    ),
    "seg_manewada_north": RoadSegment(
        id="seg_manewada_north",
        osmId="osm_mw_n_01",
        name="Manewada Road (Ajni Sq to Manewada Sq)",
        fromJunction="j_ajni",
        toJunction="j_manewada",
        roadClass=RoadClass.SECONDARY,
        lanes=2,
        lengthMeters=1800.0,
        speedLimitKmh=45.0,
        capacityVehiclesPerHour=1800,
        importance=3.9,
        betweennessCentrality=0.69,
        geometry=[
            [79.0820, 21.1189],
            [79.0890, 21.1140],
            [79.0965, 21.1095],
        ],
    ),
    "seg_hingna_north": RoadSegment(
        id="seg_hingna_north",
        osmId="osm_hg_n_01",
        name="Hingna Road Arterial (Hingna T-Point to Shankar Nagar)",
        fromJunction="j_hingna_tpoint",
        toJunction="j_shankarnagar",
        roadClass=RoadClass.PRIMARY,
        lanes=2,
        lengthMeters=2500.0,
        speedLimitKmh=50.0,
        capacityVehiclesPerHour=2200,
        importance=4.0,
        betweennessCentrality=0.72,
        geometry=[
            [79.0432, 21.1205],
            [79.0510, 21.1290],
            [79.0585, 21.1378],
        ],
    ),
}

# 3. Initial Cameras configured at strategic Nagpur junctions
NAGPUR_CAMERAS: Dict[str, Camera] = {
    "cam_sitabuldi_01": Camera(
        cameraId="cam_sitabuldi_01",
        junctionId="j_sitabuldi",
        name="Sitabuldi North (Flyover Feed)",
        lat=21.1466,
        lon=79.0834,
        sourceType="recorded",
        direction="Northbound (Towards Sadar)",
        countingLines=[
            CountingLine(id="cl_sita_n", name="Inbound North Line", p1=[79.0832, 21.1464], p2=[79.0836, 21.1468])
        ],
        queueZones=[
            QueueZone(id="qz_sita_core", name="Sitabuldi Core Box", polygon=[
                [79.0830, 21.1463], [79.0838, 21.1463], [79.0838, 21.1469], [79.0830, 21.1469]
            ])
        ],
        isCalibrated=True,
        enabled=True,
    ),
    "cam_wardha_01": Camera(
        cameraId="cam_wardha_01",
        junctionId="j_wardha_tpoint",
        name="Rahate Colony Wardha Rd Feed",
        lat=21.1278,
        lon=79.0754,
        sourceType="recorded",
        direction="Southbound (Towards Airport/MIHAN)",
        isCalibrated=True,
        enabled=True,
    ),
    "cam_medical_01": Camera(
        cameraId="cam_medical_01",
        junctionId="j_medical_sq",
        name="Medical Square Hospital Inbound Feed",
        lat=21.1351,
        lon=79.0988,
        sourceType="recorded",
        direction="Eastbound (Towards Ajni)",
        isCalibrated=True,
        enabled=True,
    ),
    "cam_central_01": Camera(
        cameraId="cam_central_01",
        junctionId="j_central_ave",
        name="Central Avenue Agrasen Sq Feed",
        lat=21.1532,
        lon=79.1055,
        sourceType="recorded",
        direction="Westbound (Towards Railway Station)",
        isCalibrated=True,
        enabled=True,
    ),
}

# 4. Initial Nagpur Traffic Police Officers
NAGPUR_OFFICERS: Dict[str, Officer] = {
    "off_101": Officer(
        id="off_101",
        name="Inspector Rajesh Sharma",
        badgeNumber="NGP-TP-101",
        rank="Traffic Inspector",
        lat=21.1450,
        lon=79.0810,
        currentJunctionId="j_sitabuldi",
        isAvailable=True,
        shiftStatus="ON_DUTY",
        contactNumber="+91-98230-10101",
    ),
    "off_102": Officer(
        id="off_102",
        name="Sub-Inspector Amit Deshmukh",
        badgeNumber="NGP-TP-102",
        rank="Sub-Inspector",
        lat=21.1290,
        lon=79.0740,
        currentJunctionId="j_wardha_tpoint",
        isAvailable=True,
        shiftStatus="ON_DUTY",
        contactNumber="+91-98230-10102",
    ),
    "off_103": Officer(
        id="off_103",
        name="Head Constable Sunita Patil",
        badgeNumber="NGP-TP-103",
        rank="Head Constable",
        lat=21.1340,
        lon=79.0970,
        currentJunctionId="j_medical_sq",
        isAvailable=True,
        shiftStatus="ON_DUTY",
        contactNumber="+91-98230-10103",
    ),
    "off_104": Officer(
        id="off_104",
        name="Constable Vikas Wankhede",
        badgeNumber="NGP-TP-104",
        rank="Patrol Officer",
        lat=21.1490,
        lon=79.0890,
        currentJunctionId="j_cotton_market",
        isAvailable=True,
        shiftStatus="ON_DUTY",
        contactNumber="+91-98230-10104",
    ),
    "off_105": Officer(
        id="off_105",
        name="Warden Manoj Meshram",
        badgeNumber="NGP-TP-105",
        rank="Traffic Warden",
        lat=21.1420,
        lon=79.0600,
        currentJunctionId="j_dharampeth",
        isAvailable=True,
        shiftStatus="ON_DUTY",
        contactNumber="+91-98230-10105",
    ),
    "off_106": Officer(
        id="off_106",
        name="Mobile Patrol Unit MP-04",
        badgeNumber="NGP-MP-04",
        rank="Rapid Response Patrol",
        lat=21.1360,
        lon=79.0600,
        currentJunctionId="j_shankarnagar",
        isAvailable=True,
        shiftStatus="ON_DUTY",
        contactNumber="+91-98230-10106",
    ),
}
